### DISCUSSION TITLE
我想用automation來控制我的冷氣，但是永遠都只會執行第一個action

### DISCUSSION THREAD

**Discussion by shaw1154** [osk2/panasonic_smart_app#82] [General]
是這樣的，我想寫一個automation已達成我按虛擬按鈕時，冷氣會切成送風並自動定時60分鐘後關機，但我怎麼寫都只有第一個action被觸發執行而已，有高手能幫我看一下嗎?
```
alias:New Automation
description: ""
trigger:
  - platform: state
    entity_id:
      - input_button.guan_ke_ting_leng_qi
condition: []
action:
  - service: number.set_value
    data:
      value: "60"
    target:
      entity_id: number.ke_ting_leng_qi_ji_ding_shi_guan_ji
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: climate.set_hvac_mode
    data:
      hvac_mode: fan_only
    target:
      entity_id: climate.ke_ting_leng_qi_ji
mode: single
```
